import com.sun.net.httpserver.*;
import java.io.*;
import java.net.*;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import javax.imageio.ImageIO;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.Executors;

public class LughFilmServer {
  static final Path ROOT=Paths.get("").toAbsolutePath().normalize(), DOWNLOADS=Paths.get(System.getProperty("user.home"),"LughFilm","downloads");
  public static void main(String[] a)throws Exception{URI home=URI.create("http://127.0.0.1:8765");HttpServer s;try{s=HttpServer.create(new InetSocketAddress("127.0.0.1",8765),0);}catch(BindException used){open(home);return;}s.createContext("/api/download",LughFilmServer::download);s.createContext("/",LughFilmServer::file);s.setExecutor(Executors.newCachedThreadPool());s.start();installTray(home,s);open(home);} static void open(URI home){try{if(Desktop.isDesktopSupported())Desktop.getDesktop().browse(home);}catch(Exception ignored){}} static void installTray(URI home,HttpServer server){if(!SystemTray.isSupported())return;try(InputStream in=LughFilmServer.class.getResourceAsStream("/lughfilm-icon.png")){Image image=ImageIO.read(in);PopupMenu menu=new PopupMenu();MenuItem show=new MenuItem("Open LughFilm"),exit=new MenuItem("Exit LughFilm");TrayIcon tray=new TrayIcon(image,"LughFilm Video Tool",menu);tray.setImageAutoSize(true);show.addActionListener(e->open(home));tray.addActionListener(e->open(home));exit.addActionListener(e->{server.stop(0);SystemTray.getSystemTray().remove(tray);System.exit(0);});menu.add(show);menu.addSeparator();menu.add(exit);SystemTray.getSystemTray().add(tray);}catch(Exception ignored){}}
  static void file(HttpExchange x)throws IOException{String p=x.getRequestURI().getPath();if(p.equals("/"))p="/lughfilm.html";if(p.equals("/lughfilm.html")){try(InputStream in=LughFilmServer.class.getResourceAsStream("/lughfilm.html")){if(in!=null){byte[] data=in.readAllBytes();x.getResponseHeaders().set("Content-Type","text/html; charset=utf-8");x.sendResponseHeaders(200,data.length);try(var o=x.getResponseBody()){o.write(data);}return;}}}Path f=ROOT.resolve(p.substring(1)).normalize();if(!f.startsWith(ROOT)||!Files.isRegularFile(f)){reply(x,404,"Not found","text/plain");return;}String t=Files.probeContentType(f);x.getResponseHeaders().set("Content-Type",t==null?"application/octet-stream":t);x.sendResponseHeaders(200,Files.size(f));try(var o=x.getResponseBody()){Files.copy(f,o);}}
  static void download(HttpExchange x)throws IOException{Path dir=null;try{if(!x.getRequestMethod().equals("POST"))throw new IllegalArgumentException("POST required.");String body=new String(x.getRequestBody().readNBytes(16384),StandardCharsets.UTF_8),url=jsonUrl(body);URI u=URI.create(url);if(u.getHost()==null||!("http".equals(u.getScheme())||"https".equals(u.getScheme())))throw new IllegalArgumentException("Enter a valid http or https video URL.");String app=ytDlp();if(app==null)throw new IllegalStateException("yt-dlp is not installed or could not be found.");Files.createDirectories(DOWNLOADS);dir=Files.createTempDirectory(DOWNLOADS,"lughfilm-");String out=dir.resolve("%(title).180B-[%(id)s].%(ext)s").toString();var cmd=List.of(app,"--no-playlist","--restrict-filenames","--max-filesize","4294967296","-f","b[ext=mp4]/b","--merge-output-format","mp4","--print","after_move:filepath","-o",out,url);Process proc=new ProcessBuilder(cmd).directory(DOWNLOADS.toFile()).redirectErrorStream(true).start();String log=new String(proc.getInputStream().readAllBytes(),StandardCharsets.UTF_8);if(proc.waitFor()!=0)throw new IllegalStateException(last(log));Path video=null;for(String line:log.split("\\R")){try{Path c=Paths.get(line.trim());if(Files.isRegularFile(c))video=c;}catch(Exception ignored){}}if(video==null)try(var files=Files.list(dir)){video=files.filter(Files::isRegularFile).findFirst().orElse(null);}if(video==null)throw new IllegalStateException("yt-dlp finished without producing a video file.");String name=video.getFileName().toString();x.getResponseHeaders().set("Content-Type","video/mp4");x.getResponseHeaders().set("X-LughFilm-Filename",name);x.getResponseHeaders().set("Cache-Control","no-store");x.sendResponseHeaders(200,Files.size(video));try(var o=x.getResponseBody()){Files.copy(video,o);}}
  catch(IllegalArgumentException|IllegalStateException e){jsonError(x,400,e.getMessage());}catch(InterruptedException e){Thread.currentThread().interrupt();jsonError(x,500,"Download was interrupted.");}catch(Exception e){jsonError(x,500,"Download failed: "+e.getMessage());}finally{if(dir!=null)remove(dir);}}
  static String ytDlp(){String local=System.getenv("LOCALAPPDATA"),app=System.getProperty("jpackage.app-path","");Path appDir=app.isBlank()?ROOT:Paths.get(app).toAbsolutePath().getParent();var choices=List.of(appDir.resolve("app/yt-dlp.exe").toString(),local+"/Microsoft/WinGet/Packages/yt-dlp.yt-dlp_Microsoft.Winget.Source_8wekyb3d8bbwe/yt-dlp.exe",local+"/Programs/Krunker Police Client/resources/yt-dlp/yt-dlp.exe","yt-dlp");for(String c:choices)try{if(new ProcessBuilder(c,"--version").redirectErrorStream(true).start().waitFor()==0)return c;}catch(Exception ignored){}return null;}
  static String jsonUrl(String s){int k=s.indexOf("\"url\"");if(k<0)throw new IllegalArgumentException("Missing video URL.");int q=s.indexOf('"',s.indexOf(':',k)+1),end=q+1;boolean esc=false;StringBuilder b=new StringBuilder();for(;end<s.length();end++){char c=s.charAt(end);if(esc){b.append(c);esc=false;}else if(c=='\\')esc=true;else if(c=='"')return b.toString();else b.append(c);}throw new IllegalArgumentException("Invalid video URL.");}
  static String last(String s){String[] l=s.strip().split("\\R");return l.length==0?"yt-dlp could not download this video.":l[l.length-1];}
  static void jsonError(HttpExchange x,int code,String m)throws IOException{reply(x,code,"{\"error\":\""+(m==null?"Unknown error":m.replace("\\","\\\\").replace("\"","\\\"").replace("\n"," "))+"\"}","application/json; charset=utf-8");}
  static void reply(HttpExchange x,int code,String text,String type)throws IOException{byte[] b=text.getBytes(StandardCharsets.UTF_8);x.getResponseHeaders().set("Content-Type",type);x.sendResponseHeaders(code,b.length);try(var o=x.getResponseBody()){o.write(b);}}
  static void remove(Path root){try(var paths=Files.walk(root)){paths.sorted(Comparator.reverseOrder()).forEach(p->{try{Files.deleteIfExists(p);}catch(IOException ignored){}});}catch(IOException ignored){}}
}